services:
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  api:
    build: .
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
    volumes:
      - .:/usr/src/app
    command: npm run start:dev
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
